# Generated by Django 3.2 on 2021-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='author_pics'),
        ),
    ]
